language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_script:
  - './node_modules/.bin/lerna run build'
  - 'if [ -n "${REACT-}" ] && [ "${TEST-}" = true ]; then sh install-relevant-react.sh && npm ls >/dev/null; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint; fi'
  - 'if [ "${TEST-}" = true ]; then npm run test:only; fi'
env:
  global:
    - TEST=true
  matrix:
    - REACT=16.5
    - REACT=16.4
    - REACT=16.3
    - REACT=16.2
    - REACT=16.1
    - REACT=15
    - REACT=0.14
sudo: false
matrix:
  fast_finish: true
  include:
      env: LINT=true TEST=false
